name: front
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  kakao_flutter_sdk: ^1.1.1
  get: ^4.6.5
  google_maps_flutter: ^2.1.8
  image_picker: ^0.8.5+3
  exif: ^3.1.1
  flutter_dotenv: ^5.0.2
  searchfield: ^0.6.6
  camera_camera: ^2.0.2
  geolocator: ^8.2.1
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/image/
    - assets/marker/
